apiVersion: v1
kind: Service
metadata:
  name: {{ include "estore.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "estore.name" . }}
    helm.sh/chart: {{ include "estore.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - name: 9080-tcp
      targetPort: 9080
      protocol: TCP
      port: 9080
  selector:
    app.kubernetes.io/name: {{ include "estore.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
